// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/OrderService.proto

package com.grpc.spring.api.order;

public interface GetOrderRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GetOrderRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string orderNo = 1;</code>
   */
  java.lang.String getOrderNo();
  /**
   * <code>string orderNo = 1;</code>
   */
  com.google.protobuf.ByteString
      getOrderNoBytes();
}
