// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/OrderService.proto

package com.grpc.spring.api.order;

public interface GetOrderReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GetOrderReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string orderNo = 1;</code>
   */
  java.lang.String getOrderNo();
  /**
   * <code>string orderNo = 1;</code>
   */
  com.google.protobuf.ByteString
      getOrderNoBytes();

  /**
   * <code>string userName = 2;</code>
   */
  java.lang.String getUserName();
  /**
   * <code>string userName = 2;</code>
   */
  com.google.protobuf.ByteString
      getUserNameBytes();

  /**
   * <code>string address = 3;</code>
   */
  java.lang.String getAddress();
  /**
   * <code>string address = 3;</code>
   */
  com.google.protobuf.ByteString
      getAddressBytes();

  /**
   * <code>int64 price = 4;</code>
   */
  long getPrice();
}
